# Generated by Django 4.0.6 on 2022-07-18 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(db_column='txt_username', max_length=32, unique=True)),
                ('email', models.EmailField(db_column='txt_email', max_length=256, unique=True)),
                ('profile_image', models.BinaryField(blank=True, db_column='bin_image', default=None, editable=True, null=True)),
                ('profile_image_name', models.CharField(blank=True, db_column='txt_image', default=None, max_length=256, null=True)),
                ('is_deleted', models.BooleanField(db_column='bool_is_deleted', default=False)),
                ('datetime', models.DateTimeField(auto_now_add=True, db_column='datetime')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'db_table': 'data_users',
                'managed': True,
            },
        ),
    ]
