# Generated by Django 4.0.6 on 2022-07-24 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_users_managers'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='extension_number',
            field=models.CharField(blank=True, db_column='txt_extension', max_length=8),
        ),
        migrations.AddField(
            model_name='users',
            name='telephon_number',
            field=models.CharField(blank=True, db_column='txt_telephone_number', max_length=16),
        ),
    ]
