# Generated by Django 4.0.6 on 2022-07-24 10:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_users_extension_number_users_telephon_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='users',
            old_name='telephon_number',
            new_name='telephone_number',
        ),
    ]
