# Generated by Django 4.0.6 on 2022-07-25 00:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_rename_telephon_number_users_telephone_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='users',
            old_name='extension_number',
            new_name='extension',
        ),
    ]
