# Generated by Django 4.0.6 on 2022-08-07 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_users_profile_image_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='profile_image_name',
            field=models.CharField(blank=True, db_column='txt_image', default=None, max_length=256, null=True),
        ),
    ]
