# Generated by Django 4.0.6 on 2022-08-08 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Providers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider_alias', models.SlugField(db_column='txt_provider_alias', max_length=128, unique=True)),
                ('provider_name', models.CharField(db_column='txt_provider_name', max_length=128, unique=True)),
            ],
            options={
                'db_table': 'catalog_providers',
                'managed': True,
            },
        ),
    ]
