# Generated by Django 4.0.6 on 2022-08-08 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_alias', models.SlugField(db_column='txt_category_alias', max_length=64, unique=True)),
                ('category_name', models.CharField(db_column='txt_category_name', max_length=64, unique=True)),
            ],
            options={
                'db_table': 'catalog_categories',
                'managed': True,
            },
        ),
    ]
