# Generated by Django 4.0.6 on 2022-07-18 05:36

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employe_id', models.SlugField(db_column='txt_employe', max_length=20, unique=True)),
                ('name', models.CharField(db_column='txt_name', default='', max_length=128)),
                ('first_lastname', models.CharField(db_column='txt_first_lastname', default='', max_length=128)),
                ('second_lastname', models.CharField(db_column='txt_second_lastname', default='', max_length=128)),
                ('is_active', models.BooleanField(db_column='bool_is_active', default=True)),
                ('is_deleted', models.BooleanField(db_column='bool_is_deleted', default=False)),
                ('register_date', models.DateField(db_column='dte_register_date', default=django.utils.timezone.now, editable=False)),
                ('datetime', models.DateTimeField(db_column='datetime', default=django.utils.timezone.now, editable=False)),
            ],
            options={
                'db_table': 'data_employes',
                'managed': True,
            },
        ),
    ]
