# Generated by Django 4.0.6 on 2022-08-07 23:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('locals', '0001_initial'),
        ('employes', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employes',
            name='local',
            field=models.ForeignKey(blank=True, db_column='int_local_id', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='local_employe', to='locals.locals'),
        ),
    ]
