# Generated by Django 4.0.6 on 2022-08-07 23:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('locals', '0001_initial'),
        ('employes', '0003_employes_local'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employes',
            name='local',
            field=models.ForeignKey(db_column='int_local_id', default=1, on_delete=django.db.models.deletion.DO_NOTHING, related_name='local_employe', to='locals.locals'),
            preserve_default=False,
        ),
    ]
