# Generated by Django 4.0.6 on 2022-08-07 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Locals',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('local_alias', models.SlugField(db_column='txt_alias', max_length=136)),
                ('local_name', models.CharField(db_column='txt_local_name', max_length=128)),
                ('street', models.CharField(db_column='txt_street', max_length=128)),
                ('number', models.CharField(db_column='txt_number', max_length=16)),
                ('postal_code', models.CharField(db_column='txt_postal_code', max_length=8)),
                ('city', models.CharField(db_column='txt_city', max_length=64)),
                ('state', models.CharField(db_column='txt_state', max_length=64)),
            ],
            options={
                'db_table': 'catalog_locals',
                'managed': True,
            },
        ),
    ]
