# Generated by Django 4.0.6 on 2022-08-09 02:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('category', '0001_initial'),
        ('providers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_alias', models.SlugField(db_column='txt_product_alias', max_length=64, unique=True)),
                ('product_code', models.CharField(db_column='txt_code', max_length=16, unique=True)),
                ('product_name', models.CharField(db_column='txt_name', max_length=64)),
                ('product_description', models.CharField(blank=True, db_column='txt_description', max_length=256, null=True)),
                ('deseable_stock', models.IntegerField(db_column='int_deseable_stock', default=32)),
                ('stock', models.IntegerField(db_column='int_stock', default=0)),
                ('category', models.ForeignKey(db_column='int_category_id', on_delete=django.db.models.deletion.DO_NOTHING, related_name='product_category', to='category.categories')),
                ('provider', models.ForeignKey(db_column='int_provider_id', on_delete=django.db.models.deletion.DO_NOTHING, related_name='product_provider', to='providers.providers')),
            ],
            options={
                'db_table': 'catalog_products',
                'managed': True,
            },
        ),
    ]
